### ISSUE TITLE
in head staat de head info dat hoef je niet zelf te schrijven

### ISSUE THREAD

**Issue by Sascha-davidson** [RalphKocken/connect-your-tribe-profile-card#2]
in het mapje naast index.js staat een mapje met foot en head. in head staan de meta tages dat hoef je niet in je index te schrijven.

![image](https://user-images.githubusercontent.com/112861160/218051957-16905906-293d-4110-8ef4-23f272bcb4cf.png)

**Comment by RalphKocken** [comment]
gefixt, thanks!
